"""empty message

Revision ID: 01ab2e161071
Revises: 84eee4156cbb
Create Date: 2024-11-27 10:32:57.461825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ab2e161071'
down_revision = '84eee4156cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('producto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('producto',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120), nullable=False),
    sa.Column('precio', sa.FLOAT(), nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
