"""empty message

Revision ID: 84eee4156cbb
Revises: ef4e11c0aacf
Create Date: 2024-11-27 10:07:09.600543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84eee4156cbb'
down_revision = 'ef4e11c0aacf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefono', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')

    # ### end Alembic commands ###
